# Generated by Django 6.1 on 2026-08-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('iqama_number', models.CharField(max_length=50, unique=True)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('iqama_expiry', models.DateField()),
                ('starting_date', models.DateField()),
                ('transfer_dates', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiving_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
