# Generated by Django 6.1.1 on 2026-09-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', 'remove_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='employee_salary',
            field=models.DecimalField(decimal_places=2, default=1200.0, max_digits=10),
        ),
    ]
