# Generated by Django 4.2.30 on 2026-09-05 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_property_employee_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id'], 'verbose_name': 'Contracting Company', 'verbose_name_plural': 'Contracting Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='company',
            name='cr_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CR Number (سجل تجاري)'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Access Status'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_employees',
            field=models.PositiveIntegerField(default=50, verbose_name='Max Workers Allowed'),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Admin / Contract Notes'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter (up to 25 workers)'), ('standard', 'Standard (up to 100 workers)'), ('enterprise', 'Enterprise (Unlimited)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Expiry Date'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='client_project',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Client Project / Work Location'),
        ),
        migrations.AlterField(
            model_name='company',
            name='admin_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client / Project Name'),
        ),
    ]
