# Generated by Django 6.1 on 2026-08-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_company_employee_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
