# Generated by Django 4.2.30 on 2026-09-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_company_options_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly / Annual'), ('one_time', 'One-time License')], default='yearly', max_length=20, verbose_name='Billing Frequency'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Recurring license fee agreed with this company', max_digits=10, verbose_name='Subscription Fee (SAR)'),
        ),
    ]
