# Generated by Django 6.1 on 2026-08-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_payment_history_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='transfer_dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
