# Generated by Django 4.2.30 on 2026-09-05 22:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0003_company_billing_cycle_company_subscription_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeproperty',
            options={'verbose_name': 'Employee Accommodation Assignment', 'verbose_name_plural': 'Employee Accommodation Assignments'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Accommodation Property', 'verbose_name_plural': 'Accommodation Properties'},
        ),
        migrations.AddField(
            model_name='employeeproperty',
            name='custom_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use property charge. Set 0.00 if client-provided for this worker.', max_digits=10, null=True, verbose_name='Custom Charge for Worker (SAR)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost charged to client. Set 0.00 if provided free by client company.', max_digits=10, verbose_name='Monthly Charge (SAR)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='employee_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Salary deduction. Set 0.00 if no cost to employee.', max_digits=10, verbose_name='Salary Base / Deduction (SAR)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(max_length=255, verbose_name='Accommodation / Camp Name'),
        ),
        migrations.CreateModel(
            name='EmployeeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('iqama_renewal', 'Iqama Renewal (تجديد إقامة)'), ('advance_salary', 'Advance Salary / Loan (سلفة راتب)'), ('transport', 'Transportation / Travel (مواصلات وترحيل)'), ('sick_leave', 'Sick Leave / Medical (إجازة مرضية وتأمين طبي)'), ('vacation', 'Vacation / Exit-Reentry / Ticket (تذاكر وتأشيرات إجازة)'), ('accrual', 'Accrual / EOSB Gratuity (مستحقات نهاية الخدمة)'), ('other', 'Other Expense (مصاريف أخرى)')], max_length=30, verbose_name='Expense Category')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount (SAR)')),
                ('expense_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Description / Notes')),
                ('deduct_from_salary', models.BooleanField(default=False, help_text='Check if this amount (e.g. advance salary) should be deducted from monthly salary payment', verbose_name='Deduct from monthly salary')),
                ('is_settled', models.BooleanField(default=False, verbose_name='Settled / Paid Off')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='employees.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Spending Record',
                'verbose_name_plural': 'Employee Spending Records',
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
