# Generated by Django 6.1 on 2026-08-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_transfer_dates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='employee',
            name='kafeel_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sponsor / Kafeel Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_status',
            field=models.CharField(choices=[('active', 'Active / Valid Iqama'), ('expired', 'Expired Iqama'), ('transfer', 'In Transfer Process'), ('exit_reentry', 'Exit / Re-entry Visa')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='transfer_dates',
            field=models.DateField(blank=True, null=True, verbose_name='Join Date'),
        ),
    ]
