# Generated by Django 4.2.30 on 2026-09-05 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeproperty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deployment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Current Deployment Start Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='deployment_status',
            field=models.CharField(choices=[('deployed', 'Deployed at Client (على رأس العمل لدى العميل)'), ('available', 'Unemployed / On Bench / Not Hired (غير مسكن / قائمة الانتظار)'), ('vacation', 'On Vacation / Leave (إجازة رسمية)'), ('terminated', 'Released / Contract Ended (منتهي العقد)')], default='available', max_length=20, verbose_name='Deployment Status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='unemployed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Demobilization / Job Loss Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='unemployed_reason',
            field=models.CharField(blank=True, help_text='e.g. Project completed at client, client cut manpower, awaiting placement', max_length=255, null=True, verbose_name='Reason Unemployed / Demobilized'),
        ),
        migrations.AddField(
            model_name='property',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Total number of bed spaces available in this camp/property.', verbose_name='Bed / Resident Capacity'),
        ),
        migrations.AddField(
            model_name='property',
            name='charge_to_client',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly amount invoiced to client company for accommodation. 0.00 if client-provided or bundled in worker rate.', max_digits=10, verbose_name='Housing Invoiced to Client (SAR/month)'),
        ),
        migrations.AddField(
            model_name='property',
            name='cost_to_company',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly rent or facility cost paid by our company to the camp landlord/operator. 0.00 if client-provided.', max_digits=10, verbose_name='Camp Rent / Cost to Company (SAR/month)'),
        ),
        migrations.AddField(
            model_name='property',
            name='housing_type',
            field=models.CharField(choices=[('client_provided', 'Client-Provided Site Camp (Free - SAR 0.00) / سكن موقع موفر من العميل'), ('company_rented', 'Company-Rented Camp / Building / سكن مستأجر من الشركة'), ('worker_provided', 'Worker Self-Housing / Allowance / سكن فردي أو بدل سكن')], default='company_rented', max_length=30, verbose_name='Housing Type / Provider'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Camp Location / Site Address'),
        ),
        migrations.AddField(
            model_name='property',
            name='worker_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Amount deducted from worker's monthly salary for housing. 0.00 if housing is provided free.", max_digits=10, verbose_name='Worker Salary Deduction (SAR/month)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Charge (SAR)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='employee_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salary Base / Deduction (SAR)'),
        ),
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Client Company Name')),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contact Person / Project Manager')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Project / Site Name')),
                ('project_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Project Location / City')),
                ('cr_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='CR / Commercial Registration #')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contract / Agreement #')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='Contract Start Date')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='Contract End Date')),
                ('status', models.CharField(choices=[('active', 'Active Client / Ongoing Project (عميل نشط)'), ('completed', 'Contract Completed (منتهي)'), ('suspended', 'Suspended / On Hold (معلق)')], default='active', max_length=20, verbose_name='Project Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes & Commercial Terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='employees.company')),
            ],
            options={
                'verbose_name': 'Client Company',
                'verbose_name_plural': 'Client Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='employees.clientcompany', verbose_name='Assigned Client Company'),
        ),
    ]
