# Generated by Django 4.2.30 on 2026-09-05 22:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_deployment_date_employee_deployment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_allow_negative',
            field=models.BooleanField(default=False, help_text='Permit worker to request advance leave beyond current accrued balance.', verbose_name='Allow Advance / Negative Leave'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_annual_leave',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text="Committed annual leave days in worker's employment contract (e.g. 21 standard, 30 for engineers, 42 for 2-year cycle).", max_digits=5, verbose_name='Contract Annual Leave (Days/Year)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_carry_forward',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Max unused leave days allowed to roll over to next year.', max_digits=5, verbose_name='Carry Forward Limit (Days)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_emergency_leave',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Emergency leave days committed in contract per year.', max_digits=5, verbose_name='Emergency / Casual Leave (Days/Year)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_negative_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Maximum advance leave days allowed if negative balance is enabled.', max_digits=5, verbose_name='Max Advance Leave (Days)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_sick_leave',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Paid sick leave days committed in contract per year.', max_digits=5, verbose_name='Paid Sick Leave (Days/Year)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_ticket_frequency',
            field=models.CharField(choices=[('every_year', 'Annual Flight Ticket (تذكرة سنوية)'), ('every_2_years', 'Every 2 Years Flight Ticket (تذكرة كل سنتين)'), ('none', 'No Flight Ticket Entitlement (بدون تذكرة سفر)')], default='every_year', max_length=50, verbose_name='Flight Ticket Entitlement'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_contract_notes',
            field=models.TextField(blank=True, help_text='Individual agreement clauses, ticket destination, visa exit re-entry terms, etc.', null=True, verbose_name='Contract Leave Stipulations / Notes'),
        ),
    ]
