# Generated by Django 4.2.30 on 2026-09-05 23:10

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0006_employee_contract_allow_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Disbursement Month')),
                ('year', models.PositiveIntegerField(verbose_name='Disbursement Year')),
                ('disbursement_date', models.DateField(default=datetime.date.today, verbose_name='Payment Date')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Contract Basic Salary')),
                ('advances_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Advances Deducted')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Other Deductions')),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Payable')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Disbursed')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer / WPS (تحويل بنكي / حماية الأجور)'), ('cash', 'Cash (نقداً)'), ('cheque', 'Cheque (شيك مصرفي)')], default='bank_transfer', max_length=30, verbose_name='Payment Method')),
                ('disbursing_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='Disbursing Account / IBAN')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Reference # / Slip #')),
                ('receipt_doc', models.FileField(blank=True, null=True, upload_to='salary_receipts/', verbose_name='Payment Receipt / Voucher')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Disbursement Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_disbursements', to='employees.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_disbursements', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Salary Disbursement',
                'verbose_name_plural': 'Salary Disbursements',
                'ordering': ['-year', '-month', '-disbursement_date', '-id'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
