# Generated by Django 4.2.30 on 2026-09-05 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0007_salarydisbursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label_note', models.CharField(blank=True, help_text='Note on who this invite is intended for', max_length=255, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
                ('created_by_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_referrals', to='employees.company')),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_referral_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'One-Time Referral Link',
                'verbose_name_plural': 'One-Time Referral Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iqama_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Iqama / National ID Number')),
                ('phone_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Mobile / WhatsApp Number')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationality')),
                ('trade', models.CharField(max_length=100, verbose_name='Trade / Craft / Position')),
                ('experience_years', models.PositiveIntegerField(default=1, verbose_name='Years of Experience')),
                ('current_city', models.CharField(max_length=100, verbose_name='Current City / Region')),
                ('iqama_transferable', models.BooleanField(default=True, verbose_name='Transferable Iqama (نقل كفالة)')),
                ('expected_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Expected Salary (SAR)')),
                ('bio_skills', models.TextField(blank=True, null=True, verbose_name='Skills & Certifications')),
                ('cv_document', models.FileField(blank=True, null=True, upload_to='candidate_cvs/', verbose_name='CV / Resume / Certificates')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Master Admin Verification (بانتظار التحقق والموافقة)'), ('active', 'Verified & Active (معتمد ونشط)'), ('hired', 'Hired / Contracted (تم التوظيف / على رأس العمل)'), ('suspended', 'Suspended / Blacklisted (موقوف / محظور)')], default='pending_approval', max_length=25)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_review_notes', models.TextField(blank=True, null=True)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jobseekers', to=settings.AUTH_USER_MODEL)),
                ('hired_as_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_candidate_profile', to='employees.employee')),
                ('hired_by_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_network_workers', to='employees.company')),
                ('referred_by_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_jobseekers', to='employees.onetimereferrallink')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Seeker Candidate',
                'verbose_name_plural': 'Job Seeker Candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Job Title / Requirement')),
                ('trade_category', models.CharField(choices=[('welding', 'Welding & Fabrication (لحام وحدادة)'), ('electrical', 'Electrical & Instrumentation (كهرباء وتحكم)'), ('civil_masonry', 'Civil & Masonry (بناء وتلييس وبلاط)'), ('carpentry', 'Carpentry & Shuttering (نجارة وحدادة مسلحة)'), ('plumbing', 'Plumbing & Pipefitting (سباكة وتمديدات)'), ('driving_heavy', 'Heavy Driver / Equipment Operator (سائق ثقيل ومشغل معدات)'), ('driving_light', 'Light Driver / Delivery (سائق خفيف وتوصيل)'), ('mechanical', 'Mechanical / HVAC (ميكانيكا وتكييف)'), ('safety_hse', 'Safety & HSE Officer (مشرف سلامة وصحة مهنية)'), ('engineering', 'Engineering & Supervision (هندسة وإشراف فني)'), ('general_labor', 'General Contracting Labor (عمالة مهنية ومساعدة)'), ('other', 'Other Specialized Trade (مهن تخصصية أخرى)')], default='general_labor', max_length=30, verbose_name='Trade Category')),
                ('workers_needed', models.PositiveIntegerField(default=1, verbose_name='Number of Workers Needed')),
                ('work_location', models.CharField(max_length=120, verbose_name='Project Location / City (e.g. Riyadh, Neom, Jubail)')),
                ('project_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Client Project Site / Subcontract')),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Salary (SAR)')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary (SAR)')),
                ('accommodation_provided', models.BooleanField(default=True, verbose_name='Accommodation Provided Free')),
                ('food_provided', models.BooleanField(default=False, verbose_name='Food or Food Allowance Provided')),
                ('transportation_provided', models.BooleanField(default=True, verbose_name='Transportation to Site Provided')),
                ('iqama_transfer_required', models.BooleanField(default=True, verbose_name='Transferable Iqama or Supply Agreement')),
                ('experience_years', models.PositiveIntegerField(default=1, verbose_name='Min Years of Experience')),
                ('description', models.TextField(verbose_name='Job Description & Required Certifications')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Master Admin Review (بانتظار موافقة الإدارة)'), ('published', 'Approved & Published (معتمد ومنشور في الشبكة)'), ('rejected', 'Rejected / Revision Requested (مرفوض)'), ('closed', 'Filled / Closed (مكتمل ومغلق)')], default='pending_approval', max_length=25)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection / Moderation Feedback')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Hot / Urgent Requirement')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jobposts', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='employees.company', verbose_name='Contracting Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manpower Job Posting',
                'verbose_name_plural': 'Manpower Job Postings',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_message', models.TextField(blank=True, null=True, verbose_name='Message / Availability Note')),
                ('status', models.CharField(choices=[('applied', 'Applied / Interested (متقدم / مهتم)'), ('contacted', 'Contacted / Interviewing (تم التواصل)'), ('accepted', 'Accepted for Onboarding (مقبول للتعاقد)'), ('declined', 'Declined / Not Suitable (غير مناسب)')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employees.jobseekerprofile')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employees.jobpost')),
            ],
            options={
                'verbose_name': 'Job Application / Match',
                'verbose_name_plural': 'Job Applications / Matches',
                'ordering': ['-applied_at'],
                'unique_together': {('job_post', 'candidate')},
            },
        ),
    ]
